ARG JAVA_VERSION=17

FROM maven:3.9.9-eclipse-temurin-${JAVA_VERSION} AS build 

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline -B

COPY src ./src 

RUN mvn clean package -DskipTests

FROM eclipse-temurin:${JAVA_VERSION}-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]


